async_slam_toolbox_node:
  ros__parameters:
    transform_publish_period: 0.02
    use_sim_time: true
    mode: mapping   #mapping建图，localization定位

    base_frame: base_footprint
    odom_frame: odom
    map_frame: map
    scan_topic: /scan        #激光雷达话题，必须和gz_bridge 中的话题一致
    odom_topic: /odom
    map_topic: /map

    #性能参数
    resolution: 0.05          #地图分辨率，单位为米/像素
    map_update_interval: 1.0 #地图更新间隔，单位为秒
    max_laser_range: 20.0    #激光雷达最大有效距离，单位为米
    min_laser_range: 0.1    
    minimum_travel_rotation: 0.1 #最小旋转角度，单位为弧度
    minimum_travel_distance: 0.1   # 机器人移动多远更新一次地图
    minimum_travel_heading: 0.1    # 机器人转多少角度更新一次地图
    throttle_scans: 2   # 每2帧处理1帧
    scan_buffer_size: 30   #激光雷达数据缓冲区大小，单位为帧数
    transform_timeout: 0.5 #tf变换超时时间，单位为秒
    link_match_minimum_response_fine: 0.05

    # 加载地图继续建图
    # map_file_name: ~/my_robot_ws/src/robot_navigation/maps/map
    # map_start_at_dock: true

    #更快、更省内存地处理大规模的位姿图优化，是slam_toolbox的默认高性能配置
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY


